### PR TITLE
Changed package.json for publish

### PR DESCRIPTION
**Pull request by lorenwest**
Hey Diego, I know I could merge to master but thought the first one I'd issue a pull request and have you look at it.

### CODE REVIEW

**Comment by lorenwest** [comment]
Looks like all travis tests aren't passing in all versions of node. I'll look into it and issue a new pull request with green travis builds.

**Comment by lorenwest** [comment]
Removed tests that didn't run on newer versions of node.

**Comment by diegopamio** [comment]
sure, go ahead, I looks like you are all set now (or do you need some extra permissions in NPM?)

**Comment by lorenwest** [comment]
Everything should be in place. I was able to update github, push the new version to NPM, and I've responded to and closed the related github issues.

I've got some ideas about the inbound IFTTT node, and will put it up when I get a chance to write and test it.

Thanks again for entrusting me to be a collaborator in this project.

**Comment by diegopamio** [comment]
Thank *you* for taking the post! I didn't realize the plugin is getting ~400 downloads/month, so is good to know that now there will be less disappointment in the world :)

**Pull request merged**
