### PR TITLE
Added error handling when receiving errors from ifttt

### PR DESCRIPTION
**Pull request by jmikerq**
this should fix issue #11, and prevents any further issues when parsing the error object returned from ifttt

### CODE REVIEW

**Comment by lorenwest** [comment]
Can you see what broke the Travis tests? Also it's hard committing new code without tests - even though it's essentially bug-fix code.

**Comment by jmikerq** [comment]
I think the errors were all related to javascript lint...... other than that, it seems like the test file ifttt-spec.js still have "TODO: Fix nock tests" for most of the test cases. Not sure what would be the correct way to add test code for now.

**Comment by lorenwest** [comment]
This looks good - thanks for your work!

**Comment by lorenwest** [comment]
Published to NPM as 0.1.0.  Still not 1.x worthy because too many NPM install warnings about outdated libraries.

**Pull request merged**
